
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const toast=m=>{const t=$('#toast');if(!t)return;t.textContent=m;t.classList.add('show');clearTimeout(window.__t);window.__t=setTimeout(()=>t.classList.remove('show'),2200)};
const path=location.pathname.split('/').pop()||'index.html';$$('.nav a').forEach(a=>{if(a.getAttribute('href')===path)a.classList.add('active')});
const profiles={healthcare:{name:'Healthcare Calm',symbol:'✚',prompt:'Build a calm healthcare portal for elderly patients with low digital confidence.',emotion:82,access:94,density:28,trust:91,motion:24,targets:90},finance:{name:'Financial Trust',symbol:'◆',prompt:'Build a high-trust personal finance workspace for first-time investors.',emotion:42,access:78,density:62,trust:96,motion:52,targets:66},gaming:{name:'Gaming Energy',symbol:'⚡',prompt:'Build a competitive gaming hub for highly engaged young players.',emotion:92,access:62,density:82,trust:54,motion:95,targets:52},government:{name:'Public Clarity',symbol:'▦',prompt:'Build a government service portal for residents completing important forms.',emotion:31,access:96,density:44,trust:98,motion:12,targets:88},kids:{name:'Kids Discovery',symbol:'★',prompt:'Build a playful learning app for curious children aged 7 to 10.',emotion:98,access:88,density:24,trust:74,motion:86,targets:96},enterprise:{name:'Enterprise Control',symbol:'▤',prompt:'Build a dense operations platform for expert logistics teams.',emotion:28,access:68,density:91,trust:87,motion:42,targets:48}};
let current=localStorage.getItem('morph-profile')||'healthcare';
function updatePreview(){const p=profiles[current],titles={healthcare:'Care that feels clear.',finance:'Know where your money stands.',gaming:'Queue up. Level up.',government:'Complete your service with confidence.',kids:'Big ideas start here!',enterprise:'Control every moving part.'},copies={healthcare:'Simple guidance, larger actions, reassuring feedback, and no unnecessary surprises.',finance:'Trusted information, precise language, and decisions that feel informed.',gaming:'Fast motion, bold contrast, compressed density, and momentum-driven interaction.',government:'Plain language, high contrast, predictable navigation, and accessible forms.',kids:'Playful discovery, large targets, friendly feedback, and motion that rewards curiosity.',enterprise:'Dense information, expert shortcuts, fast scanning, and reliable control.'};if($('#previewTitle'))$('#previewTitle').textContent=titles[current];if($('#previewCopy'))$('#previewCopy').textContent=copies[current];$$('[data-profile-name]').forEach(e=>e.textContent=p.name);$$('[data-symbol]').forEach(e=>e.textContent=p.symbol);$$('[data-prompt]').forEach(e=>{if('value'in e)e.value=p.prompt;else e.textContent=p.prompt})}
function applyProfile(key,animate=true){current=key;localStorage.setItem('morph-profile',key);document.body.className=key;const p=profiles[key],vals={emotion:p.emotion,access:p.access,density:p.density,trust:p.trust,motion:p.motion,targets:p.targets};Object.entries(vals).forEach(([id,v])=>{const i=$('#'+id),o=$(`[data-output="${id}"]`);if(i)i.value=v;if(o)o.textContent=v+'%'});if(animate){$('#morphOverlay')?.classList.add('show');setTimeout(()=>$('#morphOverlay')?.classList.remove('show'),1350)}updatePreview()}
document.addEventListener('DOMContentLoaded',()=>applyProfile(current,false));
